#!/bin/bash

if [ -f '/etc/profile' ]; then
    source /etc/profile
    jb=""
elif [ -f '/var/jb/etc/profile' ]; then
    source /var/jb/etc/profile
    jb="/var/jb"
fi

run_command() {
    sed -i "s|_jbpath_|$jb|g" $plistpath
}

if [ -d /var/opt ]; then
    optpath="/var/opt"
else
    optpath="$jb/opt"
    ln -sf $jb/opt /var/
fi

adopt="$optpath/ad"
ladapath="$adopt/LaunchDaemons"
plistpath="$ladapath/roothide-update-path.plist"

run_command $plistpath

ln -sf $plistpath $jb/usr/libexec/ad

ln -sf $adopt/libexec/ $jb/usr/libexec/ad
