#! /bin/sh -

if [ -f '/etc/profile' ]; then
	. /etc/profile
elif [ -f '/var/jb/etc/profile' ]; then
	. /var/jb/etc/profile
	jb="/var/jb"
else
	echo 'Where the fuck "profile"?' 1>&2
fi

if [ -f $jb/etc/master.passwd ]; then master="$jb/etc/master.passwd"; else printf "where the fuck 'master.passwd'?" 1>&2; fi

if [ -f $jb/etc/group ]; then group="$jb/etc/group"; else printf "where the fuck 'group'?" 1>&2; fi

add_user() {
	local username="$1"
	if [ -z $2 ]; then
		echo "I need var" 1>&2
	else
		local usergroup="$2"
		:
	fi
}
